export const brands = [
  // BRANDS
  { slug: "coca-cola", name: "Coca-Cola", color: "#ffffff", bgColor: "#CC0000", perSecond: 139000, unit: "cans opened", source: "Coca-Cola Annual Report 2023", category: "brands" },
  { slug: "mcdonalds", name: "McDonald's", color: "#ffffff", bgColor: "#FFC72C", perSecond: 2100, unit: "burgers sold", source: "McDonald's Annual Report 2023", category: "brands" },
  { slug: "google", name: "Google", color: "#ffffff", bgColor: "#4285F4", perSecond: 99000, unit: "searches made", source: "Google Stats 2023", category: "brands" },
  { slug: "whatsapp", name: "WhatsApp", color: "#ffffff", bgColor: "#25D366", perSecond: 1400000, unit: "messages sent", source: "Meta Annual Report 2023", category: "brands" },
  { slug: "netflix", name: "Netflix", color: "#ffffff", bgColor: "#E50914", perSecond: 46000, unit: "hours watched", source: "Netflix Annual Report 2023", category: "brands" },
  { slug: "amazon", name: "Amazon", color: "#ffffff", bgColor: "#FF9900", perSecond: 4400, unit: "packages shipped", source: "Amazon Annual Report 2023", category: "brands" },
  { slug: "instagram", name: "Instagram", color: "#ffffff", bgColor: "#C13584", perSecond: 1000, unit: "photos posted", source: "Meta Annual Report 2023", category: "brands" },
  { slug: "apple", name: "Apple", color: "#ffffff", bgColor: "#555555", perSecond: 588, unit: "iPhones sold", source: "Apple Annual Report 2023", category: "brands" },
  { slug: "youtube", name: "YouTube", color: "#ffffff", bgColor: "#FF0000", perSecond: 500, unit: "hours uploaded", source: "YouTube Stats 2023", category: "brands" },
  { slug: "starbucks", name: "Starbucks", color: "#ffffff", bgColor: "#00704A", perSecond: 1800, unit: "coffees served", source: "Starbucks Annual Report 2023", category: "brands" },
  { slug: "tesla", name: "Tesla", color: "#ffffff", bgColor: "#E82127", perSecond: 4, unit: "cars produced", source: "Tesla Annual Report 2023", category: "brands" },
  { slug: "spotify", name: "Spotify", color: "#ffffff", bgColor: "#1DB954", perSecond: 456000, unit: "songs played", source: "Spotify Annual Report 2023", category: "brands" },

  // LIFE
  { slug: "births", name: "Births", color: "#ffffff", bgColor: "#FF6B9D", perSecond: 4.5, unit: "babies born", source: "WHO 2023", category: "life" },
  { slug: "deaths", name: "Deaths", color: "#ffffff", bgColor: "#2C3E50", perSecond: 1.8, unit: "people died", source: "WHO 2023", category: "life" },
  { slug: "first-kisses", name: "First Kisses", color: "#ffffff", bgColor: "#E84393", perSecond: 2, unit: "first kisses happening", source: "Demographic studies 2023", category: "life" },
  { slug: "weddings", name: "Weddings", color: "#ffffff", bgColor: "#9B59B6", perSecond: 2.3, unit: "couples getting married", source: "UN Demographics 2023", category: "life" },
  { slug: "divorces", name: "Divorces", color: "#ffffff", bgColor: "#7F8C8D", perSecond: 1.1, unit: "divorces filed", source: "UN Demographics 2023", category: "life" },
  { slug: "dreams", name: "Dreams", color: "#ffffff", bgColor: "#1A1A2E", perSecond: 50000, unit: "people dreaming right now", source: "Sleep Research Society 2023", category: "life" },
  { slug: "laughs", name: "Laughs", color: "#ffffff", bgColor: "#F39C12", perSecond: 200000, unit: "people laughing right now", source: "Behavioral studies 2023", category: "life" },
  { slug: "tears", name: "Tears", color: "#ffffff", bgColor: "#5D8AA8", perSecond: 30000, unit: "people crying right now", source: "Behavioral studies 2023", category: "life" },
  { slug: "heartbeats", name: "Heartbeats", color: "#ffffff", bgColor: "#C0392B", perSecond: 600000000, unit: "heartbeats worldwide", source: "WHO 2023", category: "life" },
  { slug: "steps", name: "Steps", color: "#ffffff", bgColor: "#27AE60", perSecond: 2300000000, unit: "steps taken worldwide", source: "WHO Health Stats 2023", category: "life" },
  { slug: "photos", name: "Photos Taken", color: "#ffffff", bgColor: "#8E44AD", perSecond: 57000, unit: "photos taken", source: "Keypoint Intelligence 2023", category: "life" },
  { slug: "sleep", name: "Sleeping", color: "#ffffff", bgColor: "#2C3E50", perSecond: 100000, unit: "people falling asleep", source: "Sleep Foundation 2023", category: "life" },

  // PLANET
  { slug: "trees-cut", name: "Trees Cut", color: "#ffffff", bgColor: "#8B4513", perSecond: 1900, unit: "trees cut down", source: "FAO 2023", category: "planet" },
  { slug: "co2", name: "CO₂", color: "#ffffff", bgColor: "#2D4A1E", perSecond: 1400, unit: "tons of CO₂ emitted", source: "IEA 2023", category: "planet" },
  { slug: "plastic", name: "Plastic", color: "#ffffff", bgColor: "#1B6CA8", perSecond: 400, unit: "kg of plastic in the ocean", source: "Ocean Conservancy 2023", category: "planet" },
  { slug: "lightning", name: "Lightning", color: "#ffffff", bgColor: "#F1C40F", perSecond: 100, unit: "lightning strikes", source: "NOAA 2023", category: "planet" },
  { slug: "earthquakes", name: "Earthquakes", color: "#ffffff", bgColor: "#795548", perSecond: 0.05, unit: "earthquakes detected", source: "USGS 2023", category: "planet" },
  { slug: "species-lost", name: "Species Lost", color: "#ffffff", bgColor: "#1A3C2D", perSecond: 0.003, unit: "species going extinct", source: "IUCN 2023", category: "planet" },
  { slug: "ice-melting", name: "Ice Melting", color: "#ffffff", bgColor: "#00BCD4", perSecond: 290000, unit: "kg of arctic ice melted", source: "NASA 2023", category: "planet" },
  { slug: "solar-energy", name: "Solar Energy", color: "#ffffff", bgColor: "#FF8F00", perSecond: 1500000, unit: "kWh of solar energy generated", source: "IEA 2023", category: "planet" },
  { slug: "rain", name: "Rainfall", color: "#ffffff", bgColor: "#1565C0", perSecond: 16000000, unit: "liters of rain falling", source: "NOAA 2023", category: "planet" },
  { slug: "wind-energy", name: "Wind Energy", color: "#ffffff", bgColor: "#00838F", perSecond: 800000, unit: "kWh of wind energy generated", source: "IEA 2023", category: "planet" },
  { slug: "wildfires", name: "Wildfires", color: "#ffffff", bgColor: "#BF360C", perSecond: 0.01, unit: "wildfires started", source: "FAO 2023", category: "planet" },
  { slug: "water-used", name: "Water Used", color: "#ffffff", bgColor: "#0277BD", perSecond: 1400000, unit: "liters of fresh water used", source: "UN Water 2023", category: "planet" },

  // MONEY
  { slug: "amazon-profit", name: "Amazon Profit", color: "#ffffff", bgColor: "#FF9900", perSecond: 1270, unit: "dollars earned by Amazon", source: "Amazon Annual Report 2023", category: "money" },
  { slug: "apple-profit", name: "Apple Profit", color: "#ffffff", bgColor: "#555555", perSecond: 3040, unit: "dollars earned by Apple", source: "Apple Annual Report 2023", category: "money" },
  { slug: "world-debt", name: "World Debt", color: "#ffffff", bgColor: "#C0392B", perSecond: 130000, unit: "dollars added to world debt", source: "IMF 2023", category: "money" },
  { slug: "ad-spend", name: "Ad Spend", color: "#ffffff", bgColor: "#8E24AA", perSecond: 17000, unit: "dollars spent on advertising", source: "Statista 2023", category: "money" },
  { slug: "crypto-traded", name: "Crypto Traded", color: "#ffffff", bgColor: "#F7931A", perSecond: 230000, unit: "dollars in crypto traded", source: "CoinMarketCap 2023", category: "money" },
  { slug: "ecommerce", name: "eCommerce", color: "#ffffff", bgColor: "#00ACC1", perSecond: 110000, unit: "dollars spent online", source: "Statista 2023", category: "money" },
  { slug: "taxes-collected", name: "Taxes", color: "#ffffff", bgColor: "#37474F", perSecond: 380000, unit: "dollars in taxes collected", source: "OECD 2023", category: "money" },
  { slug: "stock-traded", name: "Stocks Traded", color: "#ffffff", bgColor: "#1B5E20", perSecond: 4600000, unit: "dollars in stocks traded", source: "NYSE/NASDAQ 2023", category: "money" },
  { slug: "remittances", name: "Remittances", color: "#ffffff", bgColor: "#4527A0", perSecond: 23000, unit: "dollars sent as remittances", source: "World Bank 2023", category: "money" },
  { slug: "luxury-goods", name: "Luxury Goods", color: "#ffffff", bgColor: "#B8860B", perSecond: 9800, unit: "dollars spent on luxury goods", source: "Bain & Company 2023", category: "money" },
  { slug: "healthcare-spend", name: "Healthcare", color: "#ffffff", bgColor: "#D32F2F", perSecond: 280000, unit: "dollars spent on healthcare", source: "WHO 2023", category: "money" },
  { slug: "gaming-revenue", name: "Gaming Revenue", color: "#ffffff", bgColor: "#6A1B9A", perSecond: 5900, unit: "dollars in gaming revenue", source: "Newzoo 2023", category: "money" },

  // INTERNET
  { slug: "emails-sent", name: "Emails Sent", color: "#ffffff", bgColor: "#1565C0", perSecond: 3400000, unit: "emails sent", source: "Statista 2023", category: "internet" },
  { slug: "tiktok-views", name: "TikTok Views", color: "#ffffff", bgColor: "#010101", perSecond: 167000, unit: "TikTok videos viewed", source: "TikTok Stats 2023", category: "internet" },
  { slug: "tweets", name: "Tweets", color: "#ffffff", bgColor: "#1DA1F2", perSecond: 6000, unit: "tweets posted", source: "Twitter/X Stats 2023", category: "internet" },
  { slug: "zoom-minutes", name: "Zoom Calls", color: "#ffffff", bgColor: "#2D8CFF", perSecond: 55000, unit: "minutes of Zoom calls", source: "Zoom Annual Report 2023", category: "internet" },
  { slug: "websites-created", name: "New Websites", color: "#ffffff", bgColor: "#00796B", perSecond: 2, unit: "new websites created", source: "Netcraft 2023", category: "internet" },
  { slug: "cybercrime", name: "Cybercrime", color: "#ffffff", bgColor: "#B71C1C", perSecond: 2400, unit: "dollars lost to cybercrime", source: "Cybersecurity Ventures 2023", category: "internet" },
  { slug: "app-downloads", name: "App Downloads", color: "#ffffff", bgColor: "#4CAF50", perSecond: 2800, unit: "apps downloaded", source: "App Annie 2023", category: "internet" },
  { slug: "data-created", name: "Data Created", color: "#ffffff", bgColor: "#37474F", perSecond: 2500000, unit: "MB of data created", source: "IDC 2023", category: "internet" },
  { slug: "spam", name: "Spam Emails", color: "#ffffff", bgColor: "#BF360C", perSecond: 2800000, unit: "spam emails sent", source: "Statista 2023", category: "internet" },
  { slug: "google-ads", name: "Google Ads", color: "#ffffff", bgColor: "#FBBC05", perSecond: 9600, unit: "dollars spent on Google Ads", source: "Google Annual Report 2023", category: "internet" },
  { slug: "netflix-streams", name: "Netflix Streams", color: "#ffffff", bgColor: "#E50914", perSecond: 29000, unit: "Netflix streams active", source: "Netflix Stats 2023", category: "internet" },
  { slug: "amazon-visits", name: "Amazon Visits", color: "#ffffff", bgColor: "#FF9900", perSecond: 75000, unit: "Amazon page visits", source: "SimilarWeb 2023", category: "internet" },

  // FOOD
  { slug: "pizzas", name: "Pizzas", color: "#ffffff", bgColor: "#C62828", perSecond: 350, unit: "pizzas eaten", source: "PMQ Pizza Magazine 2023", category: "food" },
  { slug: "burgers", name: "Burgers", color: "#ffffff", bgColor: "#E65100", perSecond: 7700, unit: "burgers consumed", source: "Food Industry Stats 2023", category: "food" },
  { slug: "cups-of-coffee", name: "Coffee", color: "#ffffff", bgColor: "#4E342E", perSecond: 29000, unit: "cups of coffee drunk", source: "ICO 2023", category: "food" },
  { slug: "bottles-of-water", name: "Water Bottles", color: "#ffffff", bgColor: "#0288D1", perSecond: 20000, unit: "plastic water bottles used", source: "Earth Policy Institute 2023", category: "food" },
  { slug: "eggs", name: "Eggs", color: "#ffffff", bgColor: "#F9A825", perSecond: 46000, unit: "eggs consumed", source: "FAO 2023", category: "food" },
  { slug: "bread", name: "Bread", color: "#ffffff", bgColor: "#8D6E63", perSecond: 32000, unit: "slices of bread eaten", source: "FAO 2023", category: "food" },
  { slug: "beer", name: "Beer", color: "#ffffff", bgColor: "#F57F17", perSecond: 18000, unit: "glasses of beer drunk", source: "Kirin Beer Report 2023", category: "food" },
  { slug: "sushi", name: "Sushi", color: "#ffffff", bgColor: "#B71C1C", perSecond: 3200, unit: "sushi pieces eaten", source: "Japan Food Industry 2023", category: "food" },
  { slug: "ice-cream", name: "Ice Cream", color: "#ffffff", bgColor: "#F48FB1", perSecond: 8900, unit: "ice creams eaten", source: "IDFA 2023", category: "food" },
  { slug: "bananas", name: "Bananas", color: "#ffffff", bgColor: "#F9A825", perSecond: 3800, unit: "bananas eaten", source: "FAO 2023", category: "food" },
  { slug: "chocolate", name: "Chocolate", color: "#ffffff", bgColor: "#3E2723", perSecond: 11000, unit: "chocolate bars eaten", source: "ICCO 2023", category: "food" },
  { slug: "wine", name: "Wine", color: "#ffffff", bgColor: "#880E4F", perSecond: 8300, unit: "glasses of wine drunk", source: "OIV 2023", category: "food" },

  // SPORTS
  { slug: "running", name: "Running", color: "#ffffff", bgColor: "#2E7D32", perSecond: 120000, unit: "people running right now", source: "RunRepeat 2023", category: "sports" },
  { slug: "gym-visits", name: "Gym Visits", color: "#ffffff", bgColor: "#1565C0", perSecond: 3400, unit: "people at the gym right now", source: "IHRSA 2023", category: "sports" },
  { slug: "footballs-sold", name: "Footballs Sold", color: "#ffffff", bgColor: "#1B5E20", perSecond: 8, unit: "footballs sold", source: "FIFA Industry Report 2023", category: "sports" },
  { slug: "swimming", name: "Swimming", color: "#ffffff", bgColor: "#006064", perSecond: 85000, unit: "people swimming right now", source: "FINA 2023", category: "sports" },
  { slug: "cycling", name: "Cycling", color: "#ffffff", bgColor: "#E65100", perSecond: 200000, unit: "people cycling right now", source: "ECF 2023", category: "sports" },
  { slug: "yoga", name: "Yoga", color: "#ffffff", bgColor: "#6A1B9A", perSecond: 95000, unit: "people doing yoga right now", source: "Yoga Alliance 2023", category: "sports" },
  { slug: "basketball", name: "Basketball", color: "#ffffff", bgColor: "#E65100", perSecond: 45000, unit: "people playing basketball", source: "FIBA 2023", category: "sports" },
  { slug: "tennis", name: "Tennis", color: "#ffffff", bgColor: "#9E9D24", perSecond: 12000, unit: "people playing tennis", source: "ITF 2023", category: "sports" },
  { slug: "nfl-revenue", name: "NFL Revenue", color: "#ffffff", bgColor: "#013369", perSecond: 540, unit: "dollars in NFL revenue", source: "NFL Annual Report 2023", category: "sports" },
  { slug: "esports", name: "eSports", color: "#ffffff", bgColor: "#311B92", perSecond: 14000000, unit: "people watching eSports", source: "Newzoo 2023", category: "sports" },
  { slug: "marathons", name: "Marathons", color: "#ffffff", bgColor: "#880E4F", perSecond: 120, unit: "marathon km run worldwide", source: "World Athletics 2023", category: "sports" },
  { slug: "sports-betting", name: "Sports Betting", color: "#ffffff", bgColor: "#1A237E", perSecond: 45000, unit: "dollars bet on sports", source: "Statista 2023", category: "sports" }
]

export type Brand = typeof brands[0]
